site_name: PT-DevOps-Task
nav:
 - Introduction: index.md
 - Task 1 - Student grades: task1.md
 - Task 2 - Log analysis: task2.md
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: docs/css
  features:
  - content.code.copy
  - content.code.highlight
  - content.code.select
markdown_extensions:
 - tables
 - attr_list
 - md_in_html
extra_css:
 - css/custom.css
